---

- name: Verify
  hosts: all
  tasks:

    - name: Get doppler version
      ansible.builtin.command: doppler --version
      changed_when: false
      register: doppler_version

    - name: Print doppler version
      ansible.builtin.debug:
        var: doppler_version.stdout

    - name: Assert doppler version
      ansible.builtin.assert:
        that:
          - doppler_version.stdout is version('v3.0.0', '>')
