---

name: Test

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux8
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10

    steps:
      - uses: actions/checkout@v3
        with:
          path: bertiewils.doppler-cli

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip ansible molecule[docker] docker

      - name: Test with molecule
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
